name: Proxy Check

on:
  schedule:
    - cron: "*/6 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          pip install pysocks

      - name: Run checker
        run: python scripts/check_proxy.py

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add public/proxies.json
          git commit -m "Update proxies" || exit 0
          git push
